# Generated by Django 3.2.3 on 2021-05-22 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40, verbose_name='descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('tipo', models.CharField(choices=[('P', 'Pagar'), ('R', 'Receber')], max_length=1)),
                ('prazo', models.BooleanField(default=False, verbose_name='prazo')),
                ('quantidade_parcelas', models.IntegerField(max_length=2, verbose_name='quantidade de parcelas')),
                ('data', models.DateField()),
                ('data_add', models.DateField(auto_now_add=True, verbose_name='Data cadastro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Dono')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('vencimento', models.DateField(verbose_name='vencimento')),
                ('pago', models.BooleanField(default=False, verbose_name='pago')),
                ('data_add', models.DateField(auto_now_add=True, verbose_name='Data cadastro')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.conta', verbose_name='conta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Dono')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='descrição')),
                ('atual', models.BooleanField(verbose_name='atual')),
                ('data_add', models.DateField(auto_now_add=True, verbose_name='Data cadastro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Dono')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_add', models.DateField(auto_now_add=True, verbose_name='Data cadastro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Dono')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
