# Generated by Django 3.2.3 on 2021-05-22 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('tipo', models.CharField(choices=[('P', 'Pagar'), ('R', 'Receber')], max_length=1)),
                ('data', models.DateField()),
                ('data_add', models.DateField(auto_now_add=True, verbose_name='Data cadastro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria', verbose_name='Categoria')),
                ('parcela', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.parcela', verbose_name='Parcela')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Dono')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
            },
        ),
    ]
