# Generated by Django 3.2.3 on 2021-05-22 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movimentacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorOrcamentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor total')),
                ('valor_disponivel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor disponível')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valor_categoria', to='core.categoria')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.orcamento')),
            ],
            options={
                'verbose_name': 'Valor Orçamentário',
                'verbose_name_plural': 'Valores Orçamentários',
            },
        ),
    ]
