# Generated by Django 3.2.3 on 2021-05-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_valororcamentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('P', 'Pagar'), ('R', 'Receber')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
