# Generated by Django 3.1.3 on 2020-11-10 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_add', models.DateField(auto_now_add=True, verbose_name='Data cadastro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Criador', to=settings.AUTH_USER_MODEL, verbose_name='Dono')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('tipo', models.CharField(max_length=1, verbose_name='Tipo')),
                ('data_add', models.DateField(auto_now_add=True, verbose_name='Data cadastro')),
                ('data', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Categoria', to='core.categoria', verbose_name='Categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Dono', to=settings.AUTH_USER_MODEL, verbose_name='Dono')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
    ]
