# Generated by Django 3.1.3 on 2020-11-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='tipo',
            field=models.CharField(choices=[('P', 'Pagar'), ('R', 'Receber')], max_length=1),
        ),
    ]
